language: node_js
node_js:
  "8"
before_install: npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - mkdir /tmp/hugo
  - wget -qO- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xz -C /tmp/hugo
  - export PATH=/tmp/hugo:$PATH
after_script: greenkeeper-lockfile-upload
