baseurl = "https://www.garrettnay.com/"
languageCode = "en-us"
title = "Garrett Nay"
theme="engimo"

pluralizeListTitles = false

[permalinks]
blog = "/:section/:slug/"

[params]
description = "Looks like Garrett finally got himself a website."
repo = "https://github.com/garrettn/garrettnay.com"
twitter = "@grrttn"
