baseurl = "https://www.garrettnay.com/"
languageCode = "en-us"
title = "Garrett Nay"

[permalinks]
post = "/:section/:title/"

[params]
description = "Looks like Garrett finally got himself a website."
repo = "https://github.com/garrettn/garrettnay.com"
twitter = "@grrttn"
