baseurl = "https://www.garrettnay.com/"
languageCode = "en-us"
title = "Garrett Nay"

[permalinks]
post = "/:year/:month/:title/"

[params]
description = "Looks like Garrett finally got himself a website."
twitter = "@grrttn"
