baseurl = "https://www.garrettnay.com/"
languageCode = "en-us"
title = "Garrett Nay"
theme="engimo"

pluralizeListTitles = false

pygmentsCodefences = true

[permalinks]
blog = "/:section/:slug/"
page = "/:slug/"

[params.assets]
customCSS = ["engimo/custom.css"]

[params.copyright]
suffix = "([License information](/license))"

[params.info]
description = "Web developer in progress"

[params.settings]
dateFormat = "2 Jan 2006"
listDateFormat = "2 Jan 2006"
hideEntryNavigation = ["page"]

[params.social]
github = "garrettn"
twitter = "@grrttn"
linkedin = "garrettnay"

[params.sidebar]
enable = "true"

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]
footer = ["social_menu"]

[[menu.main]]
name = "Blog"
url = "/blog"
weight = -3

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = -2

[[menu.main]]
name = "About"
url = "/about"
weight = -1
