baseurl = "https://www.garrettnay.com/"
languageCode = "en-us"
title = "Garrett Nay"
theme="engimo"

pluralizeListTitles = false

pygmentsCodefences = true

[permalinks]
blog = "/:section/:slug/"

[params.copyright]
suffix = "([License information](/license))"

[params.info]
description = "Web developer in progress"

[params.settings]
dateFormat = "2 Jan 2006"
listDateFormat = "2 Jan 2006"

[params.social]
github = "garrettn"
twitter = "@grrttn"
linkedin = "garrettnay"

[params.sidebar]
enable = "true"

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]
footer = ["social_menu"]
